### PR TITLE
Adding measurements to Track request

### PR DESCRIPTION
**Pull request by DevExpDev**

### CODE REVIEW

**Comment by bottlenecked** [comment]
Hi @DevExpDev, are you sure that measurements are taken into account for trackRequest calls?

I'm mostly going by what the node.js client does, and in there [trackRequest](https://github.com/microsoft/ApplicationInsights-node.js/blob/54a37587cb794233a00f44ba629904bcfbd3a659/Library/TelemetryClient.ts#L95) accepts a [RequestTelemetry](https://github.com/microsoft/ApplicationInsights-node.js/blob/develop/Declarations/Contracts/TelemetryTypes/RequestTelemetry.ts) argument which extends the [Telemetry](https://github.com/microsoft/ApplicationInsights-node.js/blob/develop/Declarations/Contracts/TelemetryTypes/Telemetry.ts) interface, and I don't see `measurements` being a field in either of these types.

Have you seen another trackRequest example where measurements are part of the payload?

**Comment by DevExpDev** [comment]
Hi @bottlenecked, yes measurements are taken into account for the trackrequests. I see "Go" is doing that..

**Comment by bottlenecked** [comment]
Hey, you're correct, I just verified that here https://github.com/microsoft/ApplicationInsights-Go/blob/master/appinsights/contracts/requestdata.go

I'll take a look at the changes and merge, thank you!

**Comment by bottlenecked** [comment]
changes incorporated and new package 0.4.1 published

**Pull request closed without merging**
